version: "3.3"
services:
 
  laravel10_phpfpm:
    build:
      args:
        user: tum
        uid: 1000
      context: .
      dockerfile: ./Dockerfile
    container_name: laravel10_phpfpm
    links:
      - laravel10_mariadb
    volumes:
      - ./docker/httpd/php.ini:/usr/local/etc/php/php.ini
      - ./:/var/www
    networks:
      - laravel10-network

  laravel10_mariadb:
    image: "mariadb:10.4.27"
    container_name: laravel10_mariadb
    restart: always
    ports:
      - 3500:3306
    volumes:
      - ./db:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: "DB_ROOT_PASSWORD"
      MARIADB_DATABASE: ${DB_DATABASE}
      MARIADB_USER: ${DB_USERNAME}
      MARIADB_PASSWORD: ${DB_PASSWORD}
      TZ: Asia/Bangkok
    networks:
      - laravel10-network

  laravel10_adminer:
    image: adminer:4.8.1
    container_name: laravel10_adminer
    environment:
    - ADMINER_DEFAULT_SERVER=laravel10_mariadb
    - ADMINER_DEFAULT_DB_DRIVER=mysql
    ports:
      - 7500:8080
    networks:
      - laravel10-network
  
  nginx:
    image: nginx:alpine
    container_name: laravel10_web
    restart: unless-stopped
    expose:
      - "8002"
    ports:
      - "8500:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx:/etc/nginx/conf.d/
    networks:
      - laravel10-network

networks:
  laravel10-network:
    driver: bridge